### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by keinstein** [yazevnul/fcai#1]
Hi,

could you add license information to your repository?

I'm looking for some FCA code that can be used in a commertial sensor product and I prefer to use an OSS library that allows such applications. This would allow me to share my improvements of the code without the need to publish confidential data. If I wrote the code myself it is hard to argue that the company should publish its sources.

**Comment by kostyaorkostya** [comment]
Hi, I'll do this on this weekend.

**Comment by kostyaorkostya** [comment]
Done in https://github.com/yazevnul/fcai/commit/4cbce0d3155c01c4dcfc602ee707c212755f5bc7.
